repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck

  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.1.0
    hooks:
      - id: epp-validate
      - id: erb-validate
      - id: puppet-lint
        args:
          - --fail-on-warnings
      - id: puppet-validate
      - id: r10k-validate
      - id: ruby-validate
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/thoughtworks/talisman # detect and prevent secrets from getting checked in
    rev: v1.11.0
    hooks:
      - id: talisman-commit
