Vagrant.require_version '>=2.2.14'
require 'vagrant-hosts'
require 'vagrant-auto_network'
require 'vagrant-dns'
COMPUTE_NODE_COUNT = 2
TOP_LEVEL_DOMAIN = 'mcdev'.freeze

Vagrant.configure('2') do |config|
  config.dns.tld = TOP_LEVEL_DOMAIN
  config.vm.box = 'geerlingguy/centos7'

  # forces to use $HOME/.vagrant.d/insecure_private_key' we need the
  # ssh key to be the same when /home get mounted on nfs
  config.ssh.insert_key = false
  config.vm.synced_folder 'shared', '/home/vagrant/shared'

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  config.vm.define 'mgmt' do |mgmt|
    mgmt.vm.hostname = 'mgmt'
    # Use vagrant-auto_network to assign an IP address.
    mgmt.vm.network :private_network, auto_network: true
    # Use vagrant-hosts to add entries to /etc/hosts for each virtual machine
    # in this file.
    mgmt.vm.provision :hosts, sync_hosts: true
    mgmt.vm.provider 'virtualbox' do |vboxmgmt|
      vboxmgmt.cpus = 2
      vboxmgmt.memory = 2048
    end
    config.vm.provision 'shell', inline: 'cp /home/vagrant/shared/puppetserver /etc/sysconfig/puppetserver'
    mgmt.vm.provision 'shell', path: 'bootstrap-server.sh'
  end

  config.vm.define 'login' do |login|
    login.vm.hostname = 'login'
    # Use vagrant-auto_network to assign an IP address.
    login.vm.network :private_network, auto_network: true
    # Use vagrant-hosts to add entries to /etc/hosts for each virtual machine
    # in this file.
    login.vm.provision :hosts, sync_hosts: true
    login.vm.provider 'virtualbox' do |vboxlogin|
      vboxlogin.cpus = 2
      vboxlogin.memory = 2048
    end
    login.vm.provision 'shell', path: 'bootstrap-agent.sh'
  end

  # Compute nodes
  (1..COMPUTE_NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.hostname = "node#{i}"
      # Use vagrant-auto_network to assign an IP address.
      subconfig.vm.network :private_network, auto_network: true
      # Use vagrant-hosts to add entries to /etc/hosts for each virtual machine
      # in this file.
      subconfig.vm.provision :hosts, sync_hosts: true
      subconfig.vm.provision 'shell', path: 'bootstrap-agent.sh'
    end
  end
end
