COMPUTE_NODE_COUNT = 2

Vagrant.configure('2') do |config|
  config.dns.tld = 'mcdev'
  config.vm.box = 'geerlingguy/centos7'

  # forces to use $HOME/.vagrant.d/insecure_private_key' we need the
  # ssh key to be the same when /home get mounted on nfs
  config.ssh.insert_key = false
  config.vm.synced_folder 'shared', '/home/vagrant/shared'

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  config.vm.define 'login' do |login|
    login.vm.hostname = 'login'
    login.vm.network 'private_network', ip: '192.168.60.3'
    login.vm.provider 'virtualbox' do |vboxlogin|
      vboxlogin.cpus = 2
      vboxlogin.memory = 2048
    end
    login.vm.provision 'shell', path: 'provision-agent.sh'
  end

  config.vm.define 'mgmt' do |mgmt|
    mgmt.vm.hostname = 'mgmt'
    mgmt.vm.network 'private_network', ip: '192.168.60.4'
    mgmt.vm.provider 'virtualbox' do |vboxmgmt|
      vboxmgmt.cpus = 2
      vboxmgmt.memory = 2048
    end
    config.vm.provision 'shell', inline: 'cp /home/vagrant/shared/puppetserver /etc/sysconfig/puppetserver'
    mgmt.vm.provision 'shell', path: 'provision-server.sh'
  end

  # Compute nodes
  (1..COMPUTE_NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network 'private_network', ip: "192.168.60.#{i + 5}"
      subconfig.vm.provision 'shell', path: 'provision-agent.sh'
    end
  end
end
